name: Docs
on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - name: Build site
        run: sbt docs/makeMicrosite
      - name: Publish site
        run: sbt docs/publishMicrosite
