name: Release
on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-gpg@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
