env:
  SCALA212: 2.12.15
  SCALA213: 2.13.8
  SCALA3: 3.3.0

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup Java and Scala
        uses: "olafurpg/setup-scala@v10"
        with:
          java-version: "adopt@1.8"
      - name: Cache sbt
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}"
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
      - name: Checking code formatting
        run: sbt formatCheck
  mdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup Java and Scala
        uses: "olafurpg/setup-scala@v10"
        with:
          java-version: "adopt@1.8"
      - name: Cache sbt
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}"
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
      - name: Check the mdoc documentation
        run: sbt docs/mdoc
  mima:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup Java and Scala
        uses: "olafurpg/setup-scala@v10"
        with:
          java-version: "adopt@1.8"
      - name: Cache sbt
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}"
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
      - name: Report binary issues
        run: "sbt ${{ matrix.project }}/mimaReportBinaryIssues"
    strategy:
      matrix:
        project:
          - coreJVM
          - coreJS
          - coreNative
          - playJson
          - playFramework
          - circeJVM
          - circeJS
          - circeNative
          - upickle
          - json4sNative
          - json4sJackson
          - argonaut
          - zioJson
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup Java and Scala
        uses: "olafurpg/setup-scala@v10"
        with:
          java-version: "adopt@1.8"
      - name: Cache sbt
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}"
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
      - name: Test
        run: "sbt ++${{ matrix.scala }} ${{ matrix.project }}/test"
    strategy:
      matrix:
        exclude:
          - project: playJson
            scala: $SCALA3
          - project: playFramework
            scala: $SCALA3
        project:
          - coreJVM
          - coreJS
          - coreNative
          - playJson
          - playFramework
          - circeJVM
          - circeJS
          - circeNative
          - upickle
          - json4sNative
          - json4sJackson
          - argonaut
          - zioJson
        scala:
          - $SCALA212
          - $SCALA213
          - $SCALA3
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
