name: CI

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

env:
  SCALA212: 2.12.x
  SCALA213: 2.13.x
  SCALA3: 3.x

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
      - name: Checking code formatting
        run: sbt formatCheck
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
      - name: Check the documentation
        run: sbt docs/makeSite
  mima:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
      - name: Report binary issues
        run: "sbt ${{ matrix.project }}/mimaReportBinaryIssues"
    strategy:
      matrix:
        project:
          - coreJVM
          - coreJS
          - coreNative
          - playJson
          - playFramework
          - circeJVM
          - circeJS
          - circeNative
          - upickleJVM
          - upickleJS
          - upickleNative
          - json4sNative
          - json4sJackson
          - argonaut
          - zioJson
  tests:
    runs-on: ubuntu-latest
    name: Tests ${{ matrix.project }} (${{ matrix.scala }})
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Test
        run: "sbt ++${{ matrix.scala }} ${{ matrix.project }}/test"
    strategy:
      matrix:
        exclude:
          - project: playFramework
            scala: $SCALA212
        project:
          - coreJVM
          - coreJS
          - coreNative
          - playJson
          - playFramework
          - circeJVM
          - circeJS
          - circeNative
          - upickleJVM
          - upickleJS
          - upickleNative
          - json4sNative
          - json4sJackson
          - argonaut
          - zioJson
        scala:
          - $SCALA212
          - $SCALA213
          - $SCALA3
